# Переменные для семейства Debian (Debian, Ubuntu)

# Системные пакеты
packages_common:
  - net-tools
  - mc
  - gpg
  - iproute2
  - iptables
  - vim
  - git
  - bash-completion
  - nfs-common
  - tar
  - ntp
  - jq
  - ipvsadm
  - python3-yaml

# Пакеты Kubernetes
packages_k8s:
  - kubectl
  - kubelet
  - kubeadm

# NTP сервис
ntp_service: ntp

# Firewall сервис (отсутствует по умолчанию)
firewall_service: ""

# HA пакеты
packages_ha:
  - keepalived
  - haproxy
