k8s_masters:
  hosts:
    # Control nodes
    control1.kryukov.local:
    # control2.kryukov.local:
    # control3.kryukov.local:
k8s_workers:
  hosts:
    # Worker nodes
    ws1.kryukov.local:
    ws2.kryukov.local:
    ws3.kryukov.local:
    ws4.kryukov.local:
k8s_cluster:
  children:
    k8s_masters:
    k8s_workers:
