k8s_masters:
  hosts:
    # Control nodes
    pr1.kryukov.local:
      ansible_host: 192.168.218.136
k8s_workers:
  hosts:
    # Worker nodes
    pr2.kryukov.local:
      ansible_host: 192.168.218.137
    pr3.kryukov.local:
      ansible_host: 192.168.218.138
    pr4.kryukov.local:
      ansible_host: 192.168.218.139
k8s_cluster:
  children:
    k8s_masters:
    k8s_workers:
