k8s_masters:
  hosts:
    # Control nodes
    pr1.kryukov.local:
      ansible_host: 192.168.218.136
k8s_workers:
  hosts:
    # Worker nodes
    pr2.kryukov.local:
      ansible_host: 192.168.218.137
    pr3.kryukov.local:
      ansible_host: 192.168.218.138
    pr4.kryukov.local:
      ansible_host: 192.168.218.139
k8s_cluster:
  children:
    k8s_masters:
    k8s_workers:
# External etcd nodes (раскомментировать при etcd_mode: "external")
# etcd_nodes:
#   hosts:
#     e1.kryukov.lan:
#       ansible_host: 192.168.218.141
#       etcd_short_name: e1
#     e2.kryukov.lan:
#       ansible_host: 192.168.218.142
#       etcd_short_name: e2
#     e3.kryukov.lan:
#       ansible_host: 192.168.218.143
#       etcd_short_name: e3
