---
- name: Checking for an odd number of nodes.
  hosts: groups['k8s_masters'][0]
  become: true
  become_user: root
    
  tasks:
    - name: Abort if an even number of nodes
      ansible.builtin.debug:
        msg: "Abort. –ên even number of nodes"
      failed_when: groups['k8s_masters'] | length | int is divisibleby 2

- name: Install packages
  hosts: k8s_cluster
  become: true
  become_user: root

  roles:
    - prepare-hosts

- name: Install Control nodes
  hosts: k8s_masters
  become: true
  become_user: root

  roles:
    - role: ha
      when: ha_cluster_virtual_ip is defined and ha_cluster_virtual_ip != ""
    - role: master
      when: inventory_hostname == groups['k8s_masters'][0]
    - role: second_controls

- name: Install worker nodes
  hosts: groups['k8s_masters'][0],k8s_workers
  become: true
  become_user: root
  roles:
    - workers
