---
- name: Install packages
  hosts: k8s_masters
  roles:
    - prepare-hosts

# - name: Install Control nodes
#   hosts: k8s_masters
#   roles:
#     - role: master
#       when: inventory_hostname == groups['k8s_masters'][0]
