# Холст для всяких тестов.
---
- name: Test playbook
  hosts: k8s_cluster
  #become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - debug:
        var=ansible_fqdn
    # - name: Get coredns service IP address
    #   shell: kubectl -n kube-system get svc kube-dns -o jsonpath='{.spec.clusterIP}'
    #   register: coreds_ip
    # - name: Check
    #   debug:
    #     msg: "Abort"
    #   #when: groups['k8s_masters'] | length | int is divisibleby 2
    #   failed_when: groups['k8s_masters'] | length | int is divisibleby 2
    
    
    # - name: facts
    #   debug:
    #     var=ansible_facts
    # - name: IP
    #   debug:
    #     var=ansible_facts.default_ipv4.address
