---
# ansible-playbook -b services/poweroff.yaml -e "target=rocky"
- name: Poweroff k8s_cluster
  hosts: "{{ target | default([]) }}"

  tasks:
    - name: Poweroff
      ansible.builtin.command: poweroff
      changed_when: true
