### Helm
- name: Установить Helm [online]
  when: k8s_install_mode == "online"
  ansible.builtin.unarchive:
    src: "https://get.helm.sh/helm-{{ helmVersion }}-linux-amd64.tar.gz"
    dest: /root/
    remote_src: true
    creates: /root/linux-amd64/helm
  register: helm_online

- name: Установить Helm [offline]
  when: k8s_install_mode == "offline"
  ansible.builtin.unarchive:
    src: "{{ playbook_dir }}/{{ k8s_offline_dir }}/utils/helm-{{ helmVersion }}-linux-amd64.tar.gz"
    dest: /root/
    creates: /root/linux-amd64/helm
  register: helm_offline

- name: Переместить helm в /usr/local/bin
  ansible.builtin.copy:
    src: /root/linux-amd64/helm
    dest: /usr/local/bin/helm
    remote_src: true
    mode: '0755'
  when: helm_online.changed or helm_offline.changed

- name: Проверить наличие helm-diff
  ansible.builtin.stat:
    path: /root/.local/share/helm/plugins/helm-diff
  register: helm_diff_plugin

- name: Установить плагин helm-diff [online]
  when:
    - not helm_diff_plugin.stat.exists
    - k8s_install_mode == "online"
  ansible.builtin.command: helm plugin install https://github.com/databus23/helm-diff

- name: Скопировать плагин helm-diff на ноду [offline]
  when:
    - not helm_diff_plugin.stat.exists
    - k8s_install_mode == "offline"
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}/{{ k8s_offline_dir }}/utils/helm-plugins/helm-diff/"
    dest: /tmp/helm-diff
    delegate_to: localhost
  register: helm_diff_copy

- name: Установить плагин helm-diff [offline]
  when:
    - not helm_diff_plugin.stat.exists
    - k8s_install_mode == "offline"
  ansible.builtin.command: helm plugin install /tmp/helm-diff

- name: Создать каталог для манифестов утилит
  ansible.builtin.file:
    path: /etc/kubernetes/utils
    state: directory
    mode: '0700'

### Priority classes
- name: Скопировать манифест priority classes
  ansible.builtin.copy:
    src: priorityclass.yaml
    dest: /etc/kubernetes/utils/priorityclass.yaml
    mode: '0600'
  register: priority_class

- name: Применить манифест priority classes
  ansible.builtin.command: kubectl apply -f /etc/kubernetes/utils/priorityclass.yaml
  when: priority_class.changed

### Cert-manager
- name: Установить cert-manager
  when: certManagerEnable
  block:
    - name: Загрузить манифест cert-manager [online]
      when: k8s_install_mode == "online"
      ansible.builtin.get_url:
        url: https://github.com/cert-manager/cert-manager/releases/download/{{ certManagerVersion }}/cert-manager.yaml
        dest: /etc/kubernetes/utils/cert-manager.yaml
        mode: '0600'
      register: cert_manager_online

    - name: Скопировать манифест cert-manager [offline]
      when: k8s_install_mode == "offline"
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/{{ k8s_offline_dir }}/utils/cert-manager.yaml"
        dest: /etc/kubernetes/utils/cert-manager.yaml
        mode: '0600'
      register: cert_manager_offline

    - name: Применить манифест cert-manager
      when: cert_manager_online.changed or cert_manager_offline.changed
      ansible.builtin.command: kubectl apply -f /etc/kubernetes/utils/cert-manager.yaml

    - name: Ожидание запуска cert-manager (2 минуты)
      ansible.builtin.wait_for:
        timeout: 120

    - name: Скопировать манифест Issuer
      ansible.builtin.copy:
        src: certs.yaml
        dest: /etc/kubernetes/utils/certs.yaml
        mode: '0600'
      register: issuer

    - name: Применить манифест Issuer
      ansible.builtin.command: kubectl apply -f /etc/kubernetes/utils/certs.yaml
      when: issuer.changed

### Metrics server
- name: Скопировать манифест metrics server
  ansible.builtin.template:
    src: metrics-server.j2
    dest: /etc/kubernetes/utils/metrics-server.yaml
    mode: '0600'
  when: metricsServerEnable
  register: metrics_server

- name: Применить манифест metrics server
  ansible.builtin.command: kubectl apply -f /etc/kubernetes/utils/metrics-server.yaml
  when: metrics_server.changed

### Nfs provisioner
- name: NFS provisioner
  ansible.builtin.template:
    src: nfs.j2
    dest: /etc/kubernetes/utils/nfs-provisioner.yaml
    mode: '0600'
  when: nfsEnable
  register: nfs

- name: Применить манифест NFS provisioner
  ansible.builtin.command: kubectl apply -f /etc/kubernetes/utils/nfs-provisioner.yaml
  when: nfs.changed

### MetalLB
- name: MetalLB
  when: metallbEnable
  block:
    - name: Добавить репозиторий MetalLB [online]
      when: k8s_install_mode == "online"
      kubernetes.core.helm_repository:
        name: metallb
        repo_url: https://metallb.github.io/metallb

    - name: Установить Helm-чарт MetalLB [online]
      when: k8s_install_mode == "online"
      kubernetes.core.helm:
        name: metallb
        chart_ref: metallb/metallb
        chart_version: "{{ metallbChartVersion }}"
        release_namespace: metallb
        create_namespace: true
        values:
          controller:
            image:
              pullPolicy: IfNotPresent
          speaker:
            image:
              pullPolicy: IfNotPresent

    - name: Установить Helm-чарт MetalLB [offline]
      when: k8s_install_mode == "offline"
      kubernetes.core.helm:
        name: metallb
        chart_ref: "{{ playbook_dir }}/{{ k8s_offline_dir }}/utils/helm-charts/metallb-{{ metallbChartVersion }}.tgz"
        release_namespace: metallb
        create_namespace: true
        values:
          controller:
            image:
              pullPolicy: IfNotPresent
          speaker:
            image:
              pullPolicy: IfNotPresent

    - name: Проверить статус MetalLB
      ansible.builtin.command: kubectl -n metallb get deployment.apps/metallb-controller -o jsonpath='{.status.readyReplicas}'
      register: metallb_controller_status
      until: metallb_controller_status.stdout | int > 0
      retries: 10
      delay: 10

    - name: Скопировать манифест пула MetalLB
      ansible.builtin.template:
        src: mlb.j2
        dest: /etc/kubernetes/utils/mlb.yaml
        mode: '0600'
      register: mlb_pool

    - name: Применить манифест пула MetalLB
      ansible.builtin.command: kubectl -n metallb apply -f /etc/kubernetes/utils/mlb.yaml
      when: mlb_pool.changed

### Ingress controller
- name: Ingress controller
  when: ingressControllerEnable
  block:
    - name: Добавить репозиторий ingress-nginx [online]
      when: k8s_install_mode == "online"
      kubernetes.core.helm_repository:
        name: ingress-nginx
        repo_url: https://kubernetes.github.io/ingress-nginx

    - name: Скопировать файл значений
      ansible.builtin.template:
        src: ingress-controller-values.j2
        dest: /etc/kubernetes/utils/ingress-controller-values.yaml
        mode: '0600'
      register: ingress_controller_values

    - name: Установить Helm-чарт ingress-nginx [online]
      when:
        - ingress_controller_values.changed
        - k8s_install_mode == "online"
      kubernetes.core.helm:
        name: ingress-nginx
        chart_ref: ingress-nginx/ingress-nginx
        chart_version: "{{ ingressControllerChartVersion }}"
        release_namespace: ingress-nginx
        create_namespace: true
        values_files:
          - /etc/kubernetes/utils/ingress-controller-values.yaml

    - name: Установить Helm-чарт ingress-nginx [offline]
      when:
        - ingress_controller_values.changed
        - k8s_install_mode == "offline"
      kubernetes.core.helm:
        name: ingress-nginx
        chart_ref: "{{ playbook_dir }}/{{ k8s_offline_dir }}/utils/helm-charts/ingress-nginx-{{ ingressControllerChartVersion }}.tgz"
        release_namespace: ingress-nginx
        create_namespace: true
        values_files:
          - /etc/kubernetes/utils/ingress-controller-values.yaml

## ArgoCD
- name: ArgoCD
  when: argoCDEnable
  block:
    - name: Добавить репозиторий ArgoCD [online]
      when: k8s_install_mode == "online"
      kubernetes.core.helm_repository:
        name: argocd
        repo_url: https://argoproj.github.io/argo-helm

    - name: Скопировать файл значений ArgoCD
      ansible.builtin.template:
        src: argo-values.j2
        dest: /etc/kubernetes/utils/argo-values.yaml
        mode: '0600'
      register: argo_values

    - name: Установить Helm-чарт ArgoCD [online]
      when:
        - argo_values.changed
        - k8s_install_mode == "online"
      kubernetes.core.helm:
        name: argocd
        chart_ref: argocd/argo-cd
        chart_version: "{{ argoCDChartVersion }}"
        release_namespace: argocd
        create_namespace: true
        values_files:
          - /etc/kubernetes/utils/argo-values.yaml

    - name: Установить Helm-чарт ArgoCD [offline]
      when:
        - argo_values.changed
        - k8s_install_mode == "offline"
      kubernetes.core.helm:
        name: argocd
        chart_ref: "{{ playbook_dir }}/{{ k8s_offline_dir }}/utils/helm-charts/argo-cd-{{ argoCDChartVersion }}.tgz"
        release_namespace: argocd
        create_namespace: true
        values_files:
          - /etc/kubernetes/utils/argo-values.yaml
