# - name: Manual start CoreDNS
#   when: k8s_middle_version >= '31'
#   block:
#     - name: Install CoreDNS copy file
#       ansible.builtin.copy:
#         src: coredns.yaml
#         dest: /etc/kubernetes/coredns.yaml
#         owner: root
#         group: root
#         mode: '0644'

#     - name: Install CoreDNS
#       ansible.builtin.command:
#         cmd: kubectl apply -f /etc/kubernetes/coredns.yaml

# Nodelocaldns

- name: Wait for coredns started
  ansible.builtin.command: "kubectl -n kube-system get svc kube-dns -o jsonpath='{.spec.clusterIP}'"
  changed_when: false
  check_mode: false
  register: result
  until: result.rc == 0
  retries: 10
  delay: 30

- name: Get coredns service IP address
  ansible.builtin.shell: |
    kubectl -n kube-system get svc kube-dns -o jsonpath='{.spec.clusterIP}'
  register: dns_ip

- set_fact:
    coredns_ip: "{{ dns_ip.stdout }}"

- name: Copy nodelocaldns manifest
  ansible.builtin.template:
    src: nodelocaldns-daemonset.j2
    dest: /etc/kubernetes/nodelocaldns-daemonset.yaml

- name: Deploy nodelocaldns
  ansible.builtin.command: kubectl apply -f /etc/kubernetes/nodelocaldns-daemonset.yaml
