---
# 1-st control node
- name: Check if kubeadm has already run
  ansible.builtin.stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: End play
  ansible.builtin.meta: end_play
  when: kubeadm_ca.stat.exists

- name: Create /etc/kubernetes directory
  ansible.builtin.file:
    path: /etc/kubernetes
    state: directory
    mode: '0700'

- name: Copy kubeadm-config.yaml
  ansible.builtin.template:
    src: kubeadm-config.j2
    dest: /etc/kubernetes/kubeadm-config.yaml
    mode: '0600'

# - name: Install Calicoctl
#   ansible.builtin.get_url:
#     url: https://github.com/projectcalico/calico/releases/download/{{ tigera_operator_version }}/calicoctl-linux-amd64
#     dest: /usr/local/bin/calicoctl
#     mode: '0755'

- name: Install Calico
  when: enableBPF is not defined
  ansible.builtin.include_tasks: calico.yaml

- name: Install Calico with BPF
  when: enableBPF is defined
  ansible.builtin.include_tasks: calico-bpf.yaml

# Почему то в 1.25 на AlmaLinux 8 не ставится enabled
- name: Kubelet enable
  ansible.builtin.service:
    name: kubelet
    state: started
    enabled: true
