---
# Первая (primary) control plane нода

- name: Проверить, кластер уже инициализирован
  ansible.builtin.stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Инициализация первого master
  when: not kubeadm_ca.stat.exists
  block:
    - name: Создать каталог /etc/kubernetes
      ansible.builtin.file:
        path: /etc/kubernetes
        state: directory
        mode: '0700'

    - name: Определить среднюю версию k8s
      ansible.builtin.set_fact:
        k8s_middle_version: "{{ kube_version[2:4] | int }}"

    - name: Скопировать kubeadm-config.yaml
      ansible.builtin.template:
        src: kubeadm-config.j2
        dest: /etc/kubernetes/kubeadm-config.yaml
        mode: '0600'

    # При offline-режиме образы загружаются из tar-файла, а не из сети
    - name: Загрузить образы k8s из архива [offline]
      when: k8s_install_mode == "offline"
      ansible.builtin.command: |
        ctr -n k8s.io images import {{ k8s_packages_remote_dir }}/k8s-images.tar

    - name: Загрузить образы k8s [online]
      when: k8s_install_mode == "online"
      ansible.builtin.command: kubeadm config images pull

    - name: Flannel
      when: cni == 'flannel'
      ansible.builtin.include_tasks: flannel.yaml

    - name: Cilium
      when: cni == 'cilium'
      block:

      - name: Установить Cilium
        when: not (cilium_kube_proxy_replacement | default(false) | bool)
        ansible.builtin.include_tasks: cilium.yaml

      - name: Установить Cilium с заменой kube-proxy
        when: cilium_kube_proxy_replacement | default(false) | bool
        ansible.builtin.include_tasks: cilium-bpf.yaml

    - name: Настроить DNS
      ansible.builtin.include_tasks: dns.yaml

    # Почему-то в 1.25 на AlmaLinux 8 не ставится enabled автоматически
    - name: Включить kubelet
      ansible.builtin.service:
        name: kubelet
        state: started
        enabled: true
