---
# Add link
- name: Add directory for config file
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: '0700'

- name: Add link for config file
  ansible.builtin.file:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    state: link
