---
# Обновление worker нод

- name: Проверка версии
  delegate_to: "{{ groups['k8s_masters'][0] }}"
  ansible.builtin.include_tasks: _version-check.yaml

- name: Обновление репозитория и пакетов
  ansible.builtin.include_tasks: _update-repo.yaml

- name: Drain worker ноды
  delegate_to: "{{ groups['k8s_masters'][0] }}"
  ansible.builtin.shell:
    cmd: kubectl drain {{ ansible_fqdn }} --ignore-daemonsets --delete-emptydir-data

- name: Обновление worker ноды
  ansible.builtin.shell:
    cmd: "kubeadm upgrade node"

- name: Перезапуск kubelet
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: kubelet

- name: Uncordon worker ноды
  delegate_to: "{{ groups['k8s_masters'][0] }}"
  ansible.builtin.shell:
    cmd: "kubectl uncordon {{ ansible_fqdn }}"
