---
# Обновление worker нод

- name: Проверка версии
  block:
    - name: Получить текущую версию ноды
      ansible.builtin.shell:
        cmd: "kubectl get nodes {{ ansible_facts['fqdn'] }} -o=jsonpath='{.status.nodeInfo.kubeletVersion}'"
      register: version_current
      delegate_to: "{{ groups['k8s_masters'][0] }}"

    - name: Версия совпадает
      ansible.builtin.debug:
        msg: "Текущая версия {{ version_current.stdout }} совпадает с целевой {{ kube_version }}"
      when: version_current.stdout is match(".*" + kube_version)

    - name: Пропустить ноду
      ansible.builtin.meta: end_host
      when: version_current.stdout is match(".*" + kube_version)

- name: Обновление репозитория и пакетов
  ansible.builtin.include_tasks: _update-repo.yaml

- name: Drain worker ноды
  delegate_to: "{{ groups['k8s_masters'][0] }}"
  ansible.builtin.shell:
    cmd: kubectl drain {{ ansible_facts['fqdn'] }} --ignore-daemonsets --delete-emptydir-data

- name: Обновление worker ноды
  ansible.builtin.shell:
    cmd: "kubeadm upgrade node"

- name: Перезапуск kubelet
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: kubelet

- name: Uncordon worker ноды
  delegate_to: "{{ groups['k8s_masters'][0] }}"
  ansible.builtin.shell:
    cmd: "kubectl uncordon {{ ansible_facts['fqdn'] }}"
