- name: Get current version of 1-st master
  shell:
    cmd: "kubectl get nodes {{ ansible_fqdn }} -o=jsonpath='{.status.nodeInfo.kubeletVersion}'"
  register: version_current_1st_master

# Сравниваем новую и текущую версию. Если они равны, ничего на этой ноде не делаем.
- name: Version check. 
  when: version_current_1st_master.stdout is match(".*" + kube_version)
  block:
    - name: Nothing todo
      debug: 
        msg: "Current cluster version {{ version_current_1st_master.stdout }} equal a new version in variables {{ kube_version }}"

    - name: Stop upgrade 1-st control
      meta: end_host

# Иначе обновим версию.

# Удалим репозитории (только online mode)
- name: Remove repository kubernetes
  when:
    - ansible_facts['os_family'] == "RedHat"
    - k8s_install_mode == "online"
  yum_repository:
    name: kubernetes
    state: absent

# Добавим репозитории (только online mode)
- name: Add repo kubernetes
  when:
    - ansible_facts['os_family'] == "RedHat"
    - k8s_install_mode == "online"
  yum_repository:
    name: kubernetes
    description: "Base programs for k8s, version: v{{ kube_version[:4] }}"
    baseurl: "https://pkgs.k8s.io/core:/stable:/v{{ kube_version[:4] }}/rpm/"
    gpgcheck: yes
    gpgkey: 
      - "https://pkgs.k8s.io/core:/stable:/v{{ kube_version[:4] }}/rpm/repodata/repomd.xml.key"

- name: Install packages dnf
  ansible.builtin.shell: |
    dnf install -y \
      {{ k8s_rpm_remote_dir }}/kubeadm-{{ kube_version }}*.rpm \
      {{ k8s_rpm_remote_dir }}/kubelet-{{ kube_version }}*.rpm \
      {{ k8s_rpm_remote_dir }}/kubectl-{{ kube_version }}*.rpm
  when: ansible_facts['os_family'] == "RedHat"

- name: Drain node
  shell: 
    cmd: kubectl drain {{ ansible_fqdn }} --ignore-daemonsets --delete-emptydir-data

# - name: Sleep for 180 seconds
#   wait_for:
#     timeout: 60

- name: Upgrade master node
  shell: 
    cmd: "kubeadm upgrade apply v{{ kube_version }} -y"

- name: Restart kubelet
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet

- name: Wait for apiserver to become ready
  ansible.builtin.command: kubectl get nodes
  register: apiserver_check
  until: apiserver_check.rc == 0
  retries: 30
  delay: 10
  changed_when: false

- name: Uncordon master node
  shell:
    cmd: "kubectl uncordon {{ ansible_fqdn }}"